# Generated by Django 4.2.26 on 2025-12-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
