# Generated by Django 4.2.26 on 2025-12-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0002_addmodules'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(blank=True, max_length=50, null=True)),
                ('Link', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
