# Generated by Django 4.2.26 on 2025-12-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0003_linktable'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtable',
            name='User',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='CyberAwarnessGameApp.usertable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linktable',
            name='Modules',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='CyberAwarnessGameApp.addmodules'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addmodules',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learningtable',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='linktable',
            name='Link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
