# Generated by Django 4.2.26 on 2025-12-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0004_learningtable_user_linktable_modules_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningtable',
            old_name='Title',
            new_name='Content',
        ),
        migrations.RemoveField(
            model_name='learningtable',
            name='User',
        ),
        migrations.RemoveField(
            model_name='linktable',
            name='Content',
        ),
        migrations.AddField(
            model_name='learningtable',
            name='Link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='learningtable',
            name='ThreatType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='linktable',
            name='Modules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyberAwarnessGameApp.learningtable'),
        ),
        migrations.DeleteModel(
            name='AddModules',
        ),
    ]
