# Generated by Django 4.2.26 on 2025-12-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0005_rename_title_learningtable_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='Emailid',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='Name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
