# Generated by Django 4.2.26 on 2025-12-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0006_alter_usertable_emailid_alter_usertable_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='username',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
