# Generated by Django 4.2.26 on 2025-12-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0007_alter_logintable_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='Rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
