# Generated by Django 4.2.26 on 2025-12-31 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0008_alter_feedbacktable_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttable',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CyberAwarnessGameApp.usertable'),
        ),
    ]
