# Generated by Django 4.2.26 on 2025-12-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0009_alter_complainttable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtable',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
