# Generated by Django 4.2.26 on 2026-01-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0010_learningtable_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=20, null=True)),
                ('option1', models.CharField(blank=True, max_length=20, null=True)),
                ('option2', models.CharField(blank=True, max_length=20, null=True)),
                ('option3', models.CharField(blank=True, max_length=20, null=True)),
                ('answer', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='linktable',
            name='Link',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
