# Generated by Django 4.2.26 on 2026-01-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0012_resulttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True)),
                ('otp', models.IntegerField(null=True)),
                ('otp_verified', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
