# Generated by Django 4.2.26 on 2026-01-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0014_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='profileImage',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
