# Generated by Django 4.2.26 on 2026-02-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0015_usertable_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningtable',
            name='Content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learningtable',
            name='ThreatType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
