# Generated by Django 4.2.26 on 2026-02-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0016_alter_learningtable_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningtable',
            name='Description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
