# Generated by Django 4.2.26 on 2026-02-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0017_alter_learningtable_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztable',
            name='question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
