# Generated by Django 4.2.26 on 2026-02-28 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CyberAwarnessGameApp', '0018_alter_quiztable_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztable',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiztable',
            name='option1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiztable',
            name='option2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiztable',
            name='option3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CertificateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificate/')),
                ('Userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CyberAwarnessGameApp.usertable')),
                ('resultid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CyberAwarnessGameApp.resulttable')),
            ],
        ),
    ]
